Render the cortellis api document for public user with and Skus null (snaoshot)
clarivate/wicked.haufe.io pull request #108
Opened 2024-02-02 06:01 UTC by darshan-clvt

### For Publiv we have enabled the cortelllis api doc 

1. only api doc 
2. no swagger button no tryout column in application
3. not skus descriptions also.
### code changes 

1. with out customID skus wont be fetched when customId is not found it will throw error 
2. we check for customId undefined 
3. we are handling null exception in for getting skus data

2024-02-02 08:31 UTC, saichrn7 requested changes

2024-02-02 08:31 UTC, saichrn7 commented on src/ui/routes/apis.js
> +                    debug("I AM IF I AM GOING FIRST")
remove this test dubug statement

2024-02-06 10:21 UTC, saichrn7 requested changes

2024-02-06 10:21 UTC, saichrn7 commented on src/ui/routes/apis.js
> +        let cortelliesapiSwap = [];
rename variable names to meaningful one..all has same swap word.

2024-02-06 10:21 UTC, saichrn7 commented on src/ui/routes/apis.js
> +                    for (let i = 0; i < cortelliesapiSwap.length; i++) {
intead of iterationg, can you check if array includes method works ?

2024-02-06 10:21 UTC, saichrn7 commented on src/ui/routes/apis.js
> +            let cortelliespiIds = req.app.portalGlobals.cortellisUi.cortelliesApi.InvestigationalApi;
follow camelCase for all variable names

2024-02-06 10:21 UTC, saichrn7 commented on src/ui/routes/apis.js
> +            let matchingValue = null;
same thing here, please write the in common place and reuse it ?

2024-02-06 10:25 UTC, darshan-clvt commented on src/ui/routes/apis.js
> +                    for (let i = 0; i < cortelliesapiSwap.length; i++) {
no it will not work Sai i have checked. i will simply pass true for other apis

2024-02-06 10:36 UTC, daru19k commented on src/ui/routes/apis.js
> +            let cortelliespiIds = req.app.portalGlobals.cortellisUi.cortelliesApi.InvestigationalApi;
sure

2024-02-06 14:04 UTC, merged