decline approvals by Date Range [snapshot]
clarivate/wicked.haufe.io pull request #52
Opened 2023-08-11 11:15 UTC by darshan-clvt

2023-08-11 13:41 UTC, uvish commented on src/api/routes/approvals.js
> +    getAllApprovals(req.app, loggedInUserId, (err, approvalInfos) => {
getAllApprovals 2 .

we can make it a single function . its doing the same thing.

2023-08-11 13:50 UTC, uvish approved these changes

2023-08-14 04:08 UTC, saichrn7 requested changes

2023-08-14 04:08 UTC, saichrn7 commented on src/api/routes/approvals.js
> +approvals.get('/byDates/:startDate/:endDate', verifyReadScope, function (req, res, next) {
@darshan-clvt , Could you add one check that validates if dates are in correct format and validates if start date shud be less that ed date.

2023-08-14 12:33 UTC, saichrn7 approved these changes

2023-08-14 12:33 UTC, saichrn7 commented on src/api/routes/approvals.js
> +        }
move this common code to one function.(line 128 --line 140)

2023-08-14 12:34 UTC, merged